# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{icehouse-right_aws}
  s.version = "2.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["RightScale, Inc."]
  s.date = %q{2010-04-14}
  s.email = %q{support@rightscale.com}
  s.extra_rdoc_files = [
    "README.txt"
  ]

  candidates = Dir.glob('{lib,test}/**/*') + ['History.txt', 'Manifest.txt', 'README.txt', 'Rakefile', 'right_aws.gemspec']
  s.files = candidates.sort
  s.homepage = %q{http://github.com/icehouse/right_aws}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Interface classes for the Amazon EC2, SQS, and S3 Web Services}
  s.test_files = [
    "test/acf/test_helper.rb",
     "test/acf/test_right_acf.rb",
     "test/awsbase/test_helper.rb",
     "test/awsbase/test_right_awsbase.rb",
     "test/ec2/test_helper.rb",
     "test/ec2/test_right_ec2.rb",
     "test/http_connection.rb",
     "test/rds/test_helper.rb",
     "test/rds/test_right_rds.rb",
     "test/s3/test_helper.rb",
     "test/s3/test_right_s3.rb",
     "test/s3/test_right_s3_stubbed.rb",
     "test/sdb/test_active_sdb.rb",
     "test/sdb/test_helper.rb",
     "test/sdb/test_right_sdb.rb",
     "test/sqs/test_helper.rb",
     "test/sqs/test_right_sqs.rb",
     "test/sqs/test_right_sqs_gen2.rb",
     "test/test_credentials.rb",
     "test/ts_right_aws.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<right_http_connection>, [">= 1.2.1"])
    else
      s.add_dependency(%q<right_http_connection>, [">= 1.2.1"])
    end
  else
    s.add_dependency(%q<right_http_connection>, [">= 1.2.1"])
  end
end
